# Generated by Django 4.2.1 on 2023-06-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='response_content_type',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='response_size',
        ),
    ]
