# Generated by Django 4.2.2 on 2023-06-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_siteinformation_article_archive_tree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='链接名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='链接描述')),
            ],
            options={
                'verbose_name_plural': '网站友情链接',
                'db_table': 'sitelink',
            },
        ),
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='URL地址')),
                ('menu_id', models.IntegerField(blank=True, null=True, verbose_name='根菜单id')),
            ],
            options={
                'verbose_name_plural': '网站菜单',
                'db_table': 'sitemenu',
            },
        ),
    ]
