# Generated by Django 4.2.1 on 2023-06-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_accesslog_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='http_protocol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='http协议'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='port_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='端口'),
        ),
    ]
