# Generated by Django 4.2.1 on 2023-06-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(null=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('browser', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.user')),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
    ]
