# Generated by Django 4.2.1 on 2023-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment_index_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=50, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
