# Generated by Django 4.2.1 on 2023-06-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_comment_reply_to_alter_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='response_code',
            new_name='status_code',
        ),
    ]
