# Generated by Django 4.2.1 on 2023-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_comment_options_remove_comment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='楼层'),
        ),
    ]
