# Generated by Django 4.2.1 on 2023-06-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_comment_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='platform',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='browser_family',
            field=models.CharField(max_length=50, null=True, verbose_name='浏览器品牌'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='browser_version',
            field=models.CharField(max_length=50, null=True, verbose_name='浏览器版本'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='http_method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP 请求方法'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='platform_name',
            field=models.CharField(max_length=50, null=True, verbose_name='操作系统名称'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='platform_version',
            field=models.CharField(max_length=50, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='referer',
            field=models.TextField(blank=True, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='request_url',
            field=models.TextField(blank=True, null=True, verbose_name='请求地址'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_agent_string',
            field=models.TextField(blank=True, null=True, verbose_name='用户代理字符串'),
        ),
    ]
