# Generated by Django 4.2.1 on 2023-06-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_comment_reply_to_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的用户名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
